routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('change-password', 'ChangePasswordController@index');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password');


Auth::routes();


Route::post('/user/update','UserController@update');
Route::get('/home', 'HomeController@index');
Route::post('/user/post', 'UserController@update');
Route::get('user/json', 'UserController@json');
Route::resource('user', 'UserController');
Route::resource('barang', 'BarangController');


Route::post('/barang/post', 'BarangController@update');
Route::get('/barang/delete/{id_barang}', 'BarangController@delete');
Route::get('/barang/edit/{id_barang}', 'BarangController@edit');
Route::post('/barang/update', 'BarangController@update');


// ruangan
Route::get('/ruangan', 'RuanganController@index');
Route::post('/ruangan/store', 'RuanganController@store');
Route::get('/ruangan/edit/{id_ruangan}', 'RuanganController@edit');
Route::post('/ruangan/update', 'RuanganController@update');
Route::get('/ruangan/hapus/{id_ruangan}', 'RuanganController@hapus');

// Kategori
Route::get('/kategori', 'KategoriController@index');
Route::post('/kategori/store', 'KategoriController@store');
Route::get('/kategori/edit/{id_Kategori}', 'KategoriController@edit');
Route::post('/kategori/update', 'KategoriController@update');
Route::get('/kategori/hapus/{id_Kategori}', 'KategoriController@hapus');

//users
Route::get('/user/edit/{id}', 'UserController@edit');
Route::get('/pj','UserController@pj');
Route::post('/store_pj','UserController@store_pj');
Route::get('/pj/edit/{id}','UserController@edit_pj');
Route::post('/user_pj/update/','UserController@update_pj');

Route::get('/rayon','UserController@rayon');
Route::post('/store_rayon','UserController@store_rayon');
Route::get('/rayon/edit/{id}','UserController@edit_rayon');
Route::post('/user_rayon/update/','UserController@update_rayon');

Route::get('/bukan_pj','UserController@bukan_pj');
Route::post('/store_bukan_pj','UserController@store_bukan_pj');
Route::get('/bukan_pj/edit/{id}','UserController@edit_bukan_pj');
Route::post('/user_bukan_pj/update/','UserController@update_bukan_pj');

// Peminjaman
Route::get('/peminjaman', 'PeminjamanController@index');
Route::post('/peminjaman/store', 'PeminjamanController@store');
Route::get('/peminjaman/edit/{id_peminjaman}', 'PeminjamanController@edit');
Route::get('/peminjaman/status/{id_peminjaman}/{id_barang}', 'PeminjamanController@status');
Route::get('/peminjaman/detail/{id_peminjaman}', 'PeminjamanController@detail');
Route::post('/peminjaman/update', 'PeminjamanController@update');
Route::get('/peminjaman/delete/{id_peminjaman}', 'PeminjamanController@delete');

//Input Barang Ruangan

Route::get('/input_ruangan', 'InputruanganController@index');
Route::post('/input_ruangan/store', 'InputruanganController@store');
Route::get('/input_ruangan/edit/{id_input_ruangan}', 'InputruanganController@edit');
Route::get('/input_ruangan/detail/{id_input_ruangan}', 'InputruanganController@detail');
Route::post('/input_ruangan/update', 'InputruanganController@update');
Route::get('/input_ruangan/delete/{id_input_ruangan}', 'InputruanganController@delete');

//keluar
Route::get('/keluar', 'KeluarController@index');
Route::post('/keluar/store', 'KeluarController@store');
Route::get('/keluar/edit/{id_keluar}', 'KeluarController@edit');
Route::get('/keluar/detail/{id_keluar}', 'KeluarController@detail');
Route::post('/keluar/update', 'KeluarController@update');
Route::get('/keluar/delete/{id_keluar}', 'KeluarController@delete');

//masuk
Route::get('/masuk', 'MasukController@index');
Route::post('/masuk/store', 'MasukController@store');
Route::get('/masuk/edit/{id_masuk}', 'MasukController@edit');
Route::get('/masuk/detail/{id_masuk}', 'MasukController@detail');
Route::post('/masuk/update', 'MasukController@update');
Route::get('/masuk/delete/{id_masuk}', 'MasukController@delete');
Route::get('/masuk/detail/{id_masuk}', 'MasukController@detail');

//rusak_ruangan
Route::get('/rusak_ruangan', 'RusakruanganController@index');
Route::get('/rusak_ruangan/edit/{id_rusak_ruangan}', 'RusakruanganController@edit');
Route::post('/rusak_ruangan/update', 'RusakruanganController@update');
Route::get('/rusak_ruangan/delete/{id_rusak_ruangan}', 'RusakruanganController@delete');
Route::get('/rusak_ruangan/status/{id_rusak_ruangan}/{id_barang_rusak}', 'RusakruanganController@status');

//rusak_luar
Route::get('/rusak_luar', 'RusakluarController@index');
Route::get('/rusak_luar/edit/{id_rusak_luar}', 'RusakluarController@edit');
Route::post('/rusak_luar/update', 'RusakluarController@update');
Route::get('/rusak_luar/delete/{id_rusak_luar}', 'RusakluarController@delete');
Route::get('/rusak_luar/status/{id_rusak_luar}/{id_barang_rusak}', 'RusakluarController@status');



//keranjang_ruangan
Route::get('/keranjang_ruangan', 'KeranjangruanganController@index');
Route::post('/keranjang_ruangan/store', 'KeranjangruanganController@store');
Route::get('/keranjang_ruangan/edit/{id_input_ruangan}', 'KeranjangruanganController@edit');
Route::post('/keranjang_ruangan/update', 'KeranjangruanganController@update');
Route::get('/keranjang_ruangan/hapus/{id_input_ruangan}', 'KeranjangruanganController@delete');

//keranjang_keluar
Route::get('/keranjang_keluar', 'KeranjangkeluarController@index');
Route::post('/keranjang_keluar/store', 'KeranjangkeluarController@store');
Route::get('/keranjang_keluar/edit/{id_keluar}', 'KeranjangkeluarController@edit');
Route::post('/keranjang_keluar/update', 'KeranjangkeluarController@update');
Route::get('/keranjang_keluar/hapus/{id_keluar}', 'KeranjangkeluarController@delete');

//keranjang_masuk
Route::get('/keranjang_masuk', 'KeranjangmasukController@index');
Route::post('/keranjang_masuk/store', 'KeranjangmasukController@store');
Route::get('/keranjang_masuk/edit/{id_masuk}', 'KeranjangmasukController@edit');
Route::post('/keranjang_masuk/update', 'KeranjangmasukController@update');
Route::get('/keranjang_masuk/hapus/{id_masuk}', 'KeranjangmasukController@delete');
Route::get('/keranjang_masuk/form_input', 'KeranjangmasukController@form_input');
Route::get('/keranjang_masuk/detail_masuk/{id}', 'KeranjangmasukController@detail_masuk');

//keranjang_peminjaman
Route::get('/keranjang_peminjaman', 'KeranjangpeminjamanController@index');
Route::post('/keranjang_peminjaman/store', 'KeranjangpeminjamanController@store');
Route::get('/keranjang_peminjaman/edit/{id_peminjaman}', 'KeranjangpeminjamanController@edit');
Route::post('/keranjang_peminjaman/update', 'KeranjangpeminjamanController@update');
Route::get('/keranjang_peminjaman/hapus/{id_peminjaman}', 'KeranjangpeminjamanController@delete');

//keranjang_rusak ruangan
Route::get('/keranjang_rusak_ruangan', 'KeranjangrusakruanganController@index');
Route::post('/keranjang_rusak_ruangan/store', 'KeranjangrusakruanganController@store');
Route::get('/keranjang_rusak_ruangan/edit/{id_rusak}', 'KeranjangrusakruanganController@edit');
Route::post('/keranjang_rusak_ruangan/update', 'KeranjangrusakruanganController@update');
Route::get('/keranjang_rusak_ruangan/hapus/{id_rusak}', 'KeranjangrusakruanganController@delete');

//keranjang_rusak luar
Route::get('/keranjang_rusak_luar', 'KeranjangrusakluarController@index');
Route::post('/keranjang_rusak_luar/store', 'KeranjangrusakluarController@store');
Route::get('/keranjang_rusak_luar/edit/{id_rusak}', 'KeranjangrusakluarController@edit');
Route::post('/keranjang_rusak_luar/update', 'KeranjangrusakluarController@update');
Route::get('/keranjang_rusak_luar/hapus/{id_rusak}', 'KeranjangrusakluarController@delete');




//Export
Route::get('/peminjaman/export_excel', 'PeminjamanController@export_excel');
Route::get('/barang_ruangan/export_excel', 'InputruanganController@export_excel');
Route::get('/keluar/export_excel', 'KeluarController@export_excel');
Route::get('/masuk/export_excel', 'MasukController@export_excel');
Route::get('/lap_barang_keluar/export_excel', 'LaporanController@export_keluar');
Route::get('/lap_barang_masuk/export_excel', 'LaporanController@export_masuk');
Route::get('/lap_barang_ruangan/export_excel', 'LaporanController@export_ruangan');
Route::get('/lap_peminjaman/export_excel', 'LaporanController@export_peminjaman');
Route::get('/lap_rusak_dalam/export_excel', 'LaporanController@export_rusak_dalam');
Route::get('/lap_rusak_luar/export_excel', 'LaporanController@export_rusak_luar');

//Select Insert
Route::get('/inputpeminjaman','KeranjangpeminjamanController@input');
Route::get('/inputmasuk', 'KeranjangmasukController@input');
Route::get('/inputkeluar', 'KeranjangkeluarController@input');
Route::get('/inputruangan', 'KeranjangruanganController@input');
Route::get('/inputrusakruangan', 'KeranjangrusakruanganController@input');
Route::get('/inputrusakluar', 'KeranjangrusakluarController@input');

//datatable
Route::get('/barang_json','DatatableController@barang_json');
Route::get('/input_ruangan_json','DatatableController@input_ruangan_json');
Route::get('/keluar_json','DatatableController@keluar_json');
Route::get('/masuk_json','DatatableController@masuk_json');
Route::get('/peminjaman_json','DatatableController@peminjaman_json');
Route::get('/rusak_ruangan_json','DatatableController@rusak_ruangan_json');
Route::get('/rusak_luar_json','DatatableController@rusak_luar_json');




Route::get('/barang/qrcode/{id_barang}','BarangController@qrcode');
Route::get('/lap_barang_masuk','LaporanController@lap_barang_masuk');
Route::post('/lap_barang_masuk_input','LaporanController@lap_barang_masuk');

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Barang;
use auth;
use DB;
use Alert;
use Illuminate\Http\Request;

class BarangController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth','Admin']);
    }


    public function index()

    {
        // $barang = DB::table('barangs')->sum('jumlah');

        $barang2 = DB::table('barangs')->get();

        // $hitung=count($barang2);

        // $kategori=DB::table('kategori')->get();

        $data = [
            'barang1' => DB::table('barangs')
                        ->join('kategori','barangs.kategori_id','=','kategori.id_kategori')
                        ->select('barangs.*','kategori.*')->get(),
            'hitung' => count($barang2),
            'kategori' => DB::table('kategori')->get(),
            'barang' =>DB::table('barangs')->sum('jumlah'),
        ];
        
        return view('barang.view')->with($data);        
        // return view('barang.view', compact('barang2','barang','hitung','kategori'));
    }

    public function store(Request $request)
    {
        DB::table('barangs')->insert([
            'id_barang' => $request->id_barang,
            'kategori_id'=>$request->kategori_id,
            'nama_barang' =>  $request->nama_barang,
            'satuan' =>  $request->satuan,
            'jumlah' => $request->jumlah,
        ]);
        Alert::success('Success', 'Data Telah Terinput');
        return redirect()->back();
    }

   
    public function edit($id)
    {

        $barang2 = DB::table('barangs')->where('id_barang', $id)->first();
        $barang = DB::table('barangs')->get();
        $kategori = DB::table('kategori')->get();

       

        return view('barang.edit', compact('barang', 'barang2','kategori'));
    }


     public function qrcode($id)
    {

        $qrcode = DB::table('barangs')->where('id_barang', $id)->first();
    
        return view('barang.qrcode', compact('qrcode'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        DB::table('input_ruangan')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
        ]);
        DB::table('keluar')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
        ]);
        DB::table('keranjang_keluar')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
        ]);
        DB::table('keranjang_masuk')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
        ]);
        DB::table('keranjang_peminjaman')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
        ]);
        DB::table('keranjang_ruangan')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
        ]);
        DB::table('masuk')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
        ]);
        DB::table('peminjaman')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
        ]);
        DB::table('keranjang_rusak_luar')->where('id_barang_rusak_luar', $request->id)->update([
            'id_barang_rusak_luar' => $request->id_barang,
        ]);
        DB::table('keranjang_rusak_ruangan')->where('id_barang_rusak', $request->id)->update([
            'id_barang_rusak' => $request->id_barang,
        ]);
        DB::table('rusak_luar')->where('id_barang_rusak_luar', $request->id)->update([
            'id_barang_rusak_luar' => $request->id_barang,
        ]);
        DB::table('rusak_ruangan')->where('id_barang_rusak', $request->id)->update([
            'id_barang_rusak' => $request->id_barang,
        ]);

        DB::table('barangs')->where('id_barang', $request->id)->update([
            'id_barang' => $request->id_barang,
            'kategori_id'=>$request->kategori_id,
            'nama_barang' => $request->nama_barang,
            'satuan' => $request->satuan,
            'jumlah' => $request->jumlah
        ]);
        // alihkan halaman ke halaman pegawai
        Alert::success('Success', 'Data Telah Terupdate');
        return redirect('/barang');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        DB::table('barangs')->where('id_barang', $id)->delete();
        Alert::success('Success', 'Data Telah Terhapus');
        return redirect()->route('barang.index');
    }
}

resources/views/barang/edit.blade.php
@extends('layouts.layout')
@section('content')
<title>Edit Data Barang</title>
<div class="card-header py-3">
  <h6 class="m-0 font-weight-bold text-dark">Edit Data</h6>
</div>
<div class="card-body">
    <div class="x_content">
            <form action="/barang/update" method="post">
                    {{ csrf_field() }}
                  <div class="form-group">
                      <label for="">Kode Barang</label>
                      <input type="hidden" name="id" value="{{$barang2->id_barang}}">
                    <input type="text" name="id_barang" class="form-control" value="{{$barang2->id_barang}}" required placeholder="Masukan Nama">
                  </div>
                  <div class="form-group">
                      <label for="">Kategori</label>
                      <select name="kategori_id" id="" class="form-control" required>
                        @foreach ($kategori as $k)
                          @if ($barang2->kategori_id==$k->id_kategori)
                              <option value="{{$k->id_kategori}}" selected>{{$k->nama_kategori}}</option>
                              @else
                              <option value="{{$k->id_kategori}}">{{$k->nama_kategori}}</option>
                          @endif
                        @endforeach
                      </select>
                    
                  </div>
                  <div class="form-group">
                        <label for="">Nama Barang</label>
                        <input type="text" name="nama_barang" class="form-control" value="{{$barang2->nama_barang}}" required placeholder="Masukan barang">
                  </div>
                  <div class="form-group">
                      <label for="">Jenis</label>
                      <input type="text" name="satuan" class="form-control" value="{{$barang2->satuan}}" required>
                  </div>
                  <div class="form-group">
                        <label for="">Jumlah</label>
                        <input type="text" name="jumlah" class="form-control" value="{{$barang2->jumlah}}" required placeholder="Masukan Ruangan">
                    </div>
                </div>
                  <button type="submit" class="btn btn-primary">Simpan</button>
            </form>

    </div>
@endsection

resources/views/barang/qrcode.blade.php
@extends('layouts.layout')
@section('content')
<title>Data Barang</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<div class="card-header py-3">
  <h6 class="m-0 font-weight-bold text-dark">QRCode</h6>
</div>
<div class="card-body text-center">
 <h3>QR Code <br> {{$qrcode->nama_barang}}</h3>
 <div id="example">
  <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')
                        ->size(150)->errorCorrection('H')
                        ->generate($qrcode->id_barang)) !!} ">
                        </div> 
                        <br>
                        
<input type="button" value="Print" class="btn btn-primary" onclick="printDiv(example);"/>
</div>

<script>
function printDiv(example) {
      var printContents = document.getElementById("example").innerHTML;    
   var originalContents = document.body.innerHTML;      
   document.body.innerHTML = printContents;     
   window.print();     
   document.body.innerHTML = originalContents;
   }
</script>

@endsection

resources/views/barang/view.blade.php
@extends('layouts.layout')
@section('content')
<title>Data Barang</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
</div>
 <div class="row"> 
  <div class="col-xl-6 col-md-12 mb-4">
    <div class="card border-left-dark shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">Barang</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{$barang}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa fa-book fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-6 col-md-12 mb-4">
    <div class="card border-left-dark shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">Jumlah Barang</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{$hitung}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-file fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
 </div>
 <div class="card shadow mb-4">
<div class="card-header py-3">
  <h6 class="m-0 font-weight-bold text-dark">Data Barang</h6>
</div>

<div class="card-body">
   
  <div class="table-responsive">
    <button class="btn btn-success" data-toggle="modal" data-target="#tambah">Tambah Data</button>
      <br>
      <br>
      <table id="example" class="table table-bordered js-basic-example dataTable" cellspacing="0">
          <thead>
            <tr>
                  <th>Kode Barang</th>
                  <th>Nama Barang</th>
                  <th>Kategori</th>
                  <th>Satuan</th>
                  <th>Jumlah Baik</th>
                  <th>Jumlah Rusak</th>
                  <th>Total</th>
                  <th>Opsi</th>
            </tr>
          </thead>
          <tbody>
            @foreach($barang1 as $b)
            <tr>
              <td>{{ $b->id_barang }}</td>
              <td>{{ $b->nama_barang }}</td>
              <td>{{ $b->nama_kategori }}</td>
              <td>{{ $b->satuan }}</td>
              <td>{{ $b->jumlah }}</td>
              <td>{{ $b->jumlah_rusak }}</td>
              <td>{{ $b->jumlah+$b->jumlah_rusak }}</td>
              <td></td>
            </tr>
            @endforeach

          </tbody>
      </table>
          
  </div>
</div>

  <div id="tambah" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Masukan Data</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <form action="{{ route('barang.store') }}" method="post">
            @csrf
          <div class="form-group">
              <label for="">Kode Barang</label>
              <input type="text" name="id_barang" class="form-control"  required>
          </div>
          <div class="form-group">
                <label for="">Nama Barang</label>
                <input type="text" name="nama_barang" class="form-control" placeholder="Masukan Nama Barang" required>
          </div>
          <div class="form-group">
                <label for="">Kategori</label>
                <select name="kategori_id" class="form-control" required>
                  <option value="" selected disabled>Pilih Kategori</option>
                   @foreach ($kategori as $k)
                    <option value="{{$k->id_kategori}}">{{$k->nama_kategori}}</option>
                   @endforeach
                </select>
          </div>
          <div class="form-group">
              <label for="">Satuan</label>
              <input type="text" name="satuan" class="form-control" placeholder="Masukan Satuan" required>
          </div>
          <div class="form-group">
                <label for="">Jumlah</label>
                <input type="number" name="jumlah" class="form-control" required placeholder="Masukan Jumlah Barang" required>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
        </div>
      </div>
    </div>
  </div>

<!--   <script>
 $(document).ready( function () {
    $('#example').DataTable({
           processing: true,
           serverSide: true,
           ajax: "/barang_json",
           columns: [
                    { data: 'id_barang', name: 'id_barang' },
                    { data: 'nama_barang', name: 'nama_barang' },
                    { data: 'nama_kategori', name: 'nama_kategori' },
                    { data: 'satuan', name: 'satuan' },
                    { data: 'jumlah', name: 'jumlah' },
                    { data: 'jumlah_rusak', name: 'jumlah_rusak' },
                     { data: 'total', name: 'total' },
                    {data: 'action', name: 'action', orderable: false},
                 ]
        });
     });
</script> -->
@endsection