routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('change-password', 'ChangePasswordController@index');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password');


Auth::routes();


Route::post('/user/update','UserController@update');
Route::get('/home', 'HomeController@index');
Route::post('/user/post', 'UserController@update');
Route::get('user/json', 'UserController@json');
Route::resource('user', 'UserController');
Route::resource('barang', 'BarangController');


Route::post('/barang/post', 'BarangController@update');
Route::get('/barang/delete/{id_barang}', 'BarangController@delete');
Route::get('/barang/edit/{id_barang}', 'BarangController@edit');
Route::post('/barang/update', 'BarangController@update');


// ruangan
Route::get('/ruangan', 'RuanganController@index');
Route::post('/ruangan/store', 'RuanganController@store');
Route::get('/ruangan/edit/{id_ruangan}', 'RuanganController@edit');
Route::post('/ruangan/update', 'RuanganController@update');
Route::get('/ruangan/hapus/{id_ruangan}', 'RuanganController@hapus');

// Kategori
Route::get('/kategori', 'KategoriController@index');
Route::post('/kategori/store', 'KategoriController@store');
Route::get('/kategori/edit/{id_Kategori}', 'KategoriController@edit');
Route::post('/kategori/update', 'KategoriController@update');
Route::get('/kategori/hapus/{id_Kategori}', 'KategoriController@hapus');

//users
Route::get('/user/edit/{id}', 'UserController@edit');
Route::get('/pj','UserController@pj');
Route::post('/store_pj','UserController@store_pj');
Route::get('/pj/edit/{id}','UserController@edit_pj');
Route::post('/user_pj/update/','UserController@update_pj');

Route::get('/rayon','UserController@rayon');
Route::post('/store_rayon','UserController@store_rayon');
Route::get('/rayon/edit/{id}','UserController@edit_rayon');
Route::post('/user_rayon/update/','UserController@update_rayon');

Route::get('/bukan_pj','UserController@bukan_pj');
Route::post('/store_bukan_pj','UserController@store_bukan_pj');
Route::get('/bukan_pj/edit/{id}','UserController@edit_bukan_pj');
Route::post('/user_bukan_pj/update/','UserController@update_bukan_pj');

// Peminjaman
Route::get('/peminjaman', 'PeminjamanController@index');
Route::post('/peminjaman/store', 'PeminjamanController@store');
Route::get('/peminjaman/edit/{id_peminjaman}', 'PeminjamanController@edit');
Route::get('/peminjaman/status/{id_peminjaman}/{id_barang}', 'PeminjamanController@status');
Route::get('/peminjaman/detail/{id_peminjaman}', 'PeminjamanController@detail');
Route::post('/peminjaman/update', 'PeminjamanController@update');
Route::get('/peminjaman/delete/{id_peminjaman}', 'PeminjamanController@delete');

//Input Barang Ruangan

Route::get('/input_ruangan', 'InputruanganController@index');
Route::post('/input_ruangan/store', 'InputruanganController@store');
Route::get('/input_ruangan/edit/{id_input_ruangan}', 'InputruanganController@edit');
Route::get('/input_ruangan/detail/{id_input_ruangan}', 'InputruanganController@detail');
Route::post('/input_ruangan/update', 'InputruanganController@update');
Route::get('/input_ruangan/delete/{id_input_ruangan}', 'InputruanganController@delete');

//keluar
Route::get('/keluar', 'KeluarController@index');
Route::post('/keluar/store', 'KeluarController@store');
Route::get('/keluar/edit/{id_keluar}', 'KeluarController@edit');
Route::get('/keluar/detail/{id_keluar}', 'KeluarController@detail');
Route::post('/keluar/update', 'KeluarController@update');
Route::get('/keluar/delete/{id_keluar}', 'KeluarController@delete');

//masuk
Route::get('/masuk', 'MasukController@index');
Route::post('/masuk/store', 'MasukController@store');
Route::get('/masuk/edit/{id_masuk}', 'MasukController@edit');
Route::get('/masuk/detail/{id_masuk}', 'MasukController@detail');
Route::post('/masuk/update', 'MasukController@update');
Route::get('/masuk/delete/{id_masuk}', 'MasukController@delete');
Route::get('/masuk/detail/{id_masuk}', 'MasukController@detail');

//rusak_ruangan
Route::get('/rusak_ruangan', 'RusakruanganController@index');
Route::get('/rusak_ruangan/edit/{id_rusak_ruangan}', 'RusakruanganController@edit');
Route::post('/rusak_ruangan/update', 'RusakruanganController@update');
Route::get('/rusak_ruangan/delete/{id_rusak_ruangan}', 'RusakruanganController@delete');
Route::get('/rusak_ruangan/status/{id_rusak_ruangan}/{id_barang_rusak}', 'RusakruanganController@status');

//rusak_luar
Route::get('/rusak_luar', 'RusakluarController@index');
Route::get('/rusak_luar/edit/{id_rusak_luar}', 'RusakluarController@edit');
Route::post('/rusak_luar/update', 'RusakluarController@update');
Route::get('/rusak_luar/delete/{id_rusak_luar}', 'RusakluarController@delete');
Route::get('/rusak_luar/status/{id_rusak_luar}/{id_barang_rusak}', 'RusakluarController@status');



//keranjang_ruangan
Route::get('/keranjang_ruangan', 'KeranjangruanganController@index');
Route::post('/keranjang_ruangan/store', 'KeranjangruanganController@store');
Route::get('/keranjang_ruangan/edit/{id_input_ruangan}', 'KeranjangruanganController@edit');
Route::post('/keranjang_ruangan/update', 'KeranjangruanganController@update');
Route::get('/keranjang_ruangan/hapus/{id_input_ruangan}', 'KeranjangruanganController@delete');

//keranjang_keluar
Route::get('/keranjang_keluar', 'KeranjangkeluarController@index');
Route::post('/keranjang_keluar/store', 'KeranjangkeluarController@store');
Route::get('/keranjang_keluar/edit/{id_keluar}', 'KeranjangkeluarController@edit');
Route::post('/keranjang_keluar/update', 'KeranjangkeluarController@update');
Route::get('/keranjang_keluar/hapus/{id_keluar}', 'KeranjangkeluarController@delete');

//keranjang_masuk
Route::get('/keranjang_masuk', 'KeranjangmasukController@index');
Route::post('/keranjang_masuk/store', 'KeranjangmasukController@store');
Route::get('/keranjang_masuk/edit/{id_masuk}', 'KeranjangmasukController@edit');
Route::post('/keranjang_masuk/update', 'KeranjangmasukController@update');
Route::get('/keranjang_masuk/hapus/{id_masuk}', 'KeranjangmasukController@delete');
Route::get('/keranjang_masuk/form_input', 'KeranjangmasukController@form_input');
Route::get('/keranjang_masuk/detail_masuk/{id}', 'KeranjangmasukController@detail_masuk');

//keranjang_peminjaman
Route::get('/keranjang_peminjaman', 'KeranjangpeminjamanController@index');
Route::post('/keranjang_peminjaman/store', 'KeranjangpeminjamanController@store');
Route::get('/keranjang_peminjaman/edit/{id_peminjaman}', 'KeranjangpeminjamanController@edit');
Route::post('/keranjang_peminjaman/update', 'KeranjangpeminjamanController@update');
Route::get('/keranjang_peminjaman/hapus/{id_peminjaman}', 'KeranjangpeminjamanController@delete');

//keranjang_rusak ruangan
Route::get('/keranjang_rusak_ruangan', 'KeranjangrusakruanganController@index');
Route::post('/keranjang_rusak_ruangan/store', 'KeranjangrusakruanganController@store');
Route::get('/keranjang_rusak_ruangan/edit/{id_rusak}', 'KeranjangrusakruanganController@edit');
Route::post('/keranjang_rusak_ruangan/update', 'KeranjangrusakruanganController@update');
Route::get('/keranjang_rusak_ruangan/hapus/{id_rusak}', 'KeranjangrusakruanganController@delete');

//keranjang_rusak luar
Route::get('/keranjang_rusak_luar', 'KeranjangrusakluarController@index');
Route::post('/keranjang_rusak_luar/store', 'KeranjangrusakluarController@store');
Route::get('/keranjang_rusak_luar/edit/{id_rusak}', 'KeranjangrusakluarController@edit');
Route::post('/keranjang_rusak_luar/update', 'KeranjangrusakluarController@update');
Route::get('/keranjang_rusak_luar/hapus/{id_rusak}', 'KeranjangrusakluarController@delete');




//Export
Route::get('/peminjaman/export_excel', 'PeminjamanController@export_excel');
Route::get('/barang_ruangan/export_excel', 'InputruanganController@export_excel');
Route::get('/keluar/export_excel', 'KeluarController@export_excel');
Route::get('/masuk/export_excel', 'MasukController@export_excel');
Route::get('/lap_barang_keluar/export_excel', 'LaporanController@export_keluar');
Route::get('/lap_barang_masuk/export_excel', 'LaporanController@export_masuk');
Route::get('/lap_barang_ruangan/export_excel', 'LaporanController@export_ruangan');
Route::get('/lap_peminjaman/export_excel', 'LaporanController@export_peminjaman');
Route::get('/lap_rusak_dalam/export_excel', 'LaporanController@export_rusak_dalam');
Route::get('/lap_rusak_luar/export_excel', 'LaporanController@export_rusak_luar');

//Select Insert
Route::get('/inputpeminjaman','KeranjangpeminjamanController@input');
Route::get('/inputmasuk', 'KeranjangmasukController@input');
Route::get('/inputkeluar', 'KeranjangkeluarController@input');
Route::get('/inputruangan', 'KeranjangruanganController@input');
Route::get('/inputrusakruangan', 'KeranjangrusakruanganController@input');
Route::get('/inputrusakluar', 'KeranjangrusakluarController@input');

//datatable
Route::get('/barang_json','DatatableController@barang_json');
Route::get('/input_ruangan_json','DatatableController@input_ruangan_json');
Route::get('/keluar_json','DatatableController@keluar_json');
Route::get('/masuk_json','DatatableController@masuk_json');
Route::get('/peminjaman_json','DatatableController@peminjaman_json');
Route::get('/rusak_ruangan_json','DatatableController@rusak_ruangan_json');
Route::get('/rusak_luar_json','DatatableController@rusak_luar_json');




Route::get('/barang/qrcode/{id_barang}','BarangController@qrcode');
Route::get('/lap_barang_masuk','LaporanController@lap_barang_masuk');
Route::post('/lap_barang_masuk_input','LaporanController@lap_barang_masuk');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','username','level','id_ruangan'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use DB;
use DataTables;
use Alert;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{


    public function AuthRouteAPI(Request $request)
    {
        return $request->user();
    }

    public function index2()
    {
        return view('auth.login');
    }

    public function index()
    {


        $user = DB::table("users")->where('level','admin')->get();
        return view('user.view', compact('user'));
    }

    public function pj()
    {
        $user = DB::table("users")->where('level','pj')->get();
        $ruangan=DB::table('ruangan')->get();
        return view('pj.view', compact('user','ruangan'));
    }

    public function rayon()
    {

        $user = DB::table("users")->where('level','rayon')->get();

        $ruangan=DB::table('ruangan')->get();

        return view('rayon.view', compact('user','ruangan'));
    }

     public function bukan_pj()
    {

        $user = DB::table("users")->where('level','bukan_pj')->get();

        return view('bukan_pj.view', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    { }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      
        $request->validate([
            'email'=>'required|unique:users',
            'username' => 'required|unique:users',
        ]);

        $password = Hash::make($request->password);
        $data = array_replace($request->all(), ['password' => $password]);

        User::create($data);
        Alert::success('Success', 'Data Telah Terinput');
        return redirect()->back();
    }

    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user2 = DB::table('users')->where('id', $id)->first();
        $user = DB::table('users')->get();

        $ruangan = DB::table('ruangan')->get();

        return view('user.edit', compact('user', 'ruangan', 'user2'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        
        DB::table('users')->where('id',$request->id)->update([
            'name'=>$request->name,
            'email'=>$request->email,
            'username'=>$request->username
        ]);

        Alert::success('Success', 'Data Telah Terupdate');
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        Alert::success('Success', 'Data Telah Terhapus');
        return redirect()->back();
    }

    //pj

    public function store_pj(Request $request)
    {
      
        $request->validate([
            'email'=>'required|unique:users',
            'username' => 'required|unique:users',
        ]);

        $password = Hash::make($request->password);
        $data = array_replace($request->all(), ['password' => $password]);

        User::create($data);
        Alert::success('Success', 'Data Telah Terinput');
        return redirect()->back();
    }

    public function edit_pj($id)
    {
        $user2 = DB::table('users')->where('id', $id)->first();
        

        $ruangan = DB::table('ruangan')->get();

        return view('pj.edit', compact('ruangan', 'user2'));
    }

    public function update_pj(Request $request)
    {
        
        DB::table('users')->where('id',$request->id)->update([
            'name'=>$request->name,
            'email'=>$request->email,
            'username'=>$request->username,
            
        ]);

        Alert::success('Success', 'Data Telah Terupdate');
        return redirect('/pj');
    }

    //rayon

    public function store_rayon(Request $request)
    {
      
        $request->validate([
            'email'=>'required|unique:users',
            'username' => 'required|unique:users',
        ]);

        $password = Hash::make($request->password);
        $data = array_replace($request->all(), ['password' => $password]);

        User::create($data);
        Alert::success('Success', 'Data Telah Terinput');
        return redirect()->back();
    }

    public function edit_rayon($id)
    {
        $user2 = DB::table('users')->where('id', $id)->first();
        

        $ruangan = DB::table('ruangan')->get();

        return view('rayon.edit', compact('ruangan', 'user2'));
    }

    public function update_rayon(Request $request)
    {
        
        DB::table('users')->where('id',$request->id)->update([
            'name'=>$request->name,
            'email'=>$request->email,
            'username'=>$request->username,
            
        ]);

        Alert::success('Success', 'Data Telah Terupdate');
        return redirect('/rayon');
    }

    //bukan pj

    public function store_bukan_pj(Request $request)
    {
      
        $request->validate([
            'email'=>'required|unique:users',
            'username' => 'required|unique:users',
        ]);

        $password = Hash::make($request->password);
        $data = array_replace($request->all(), ['password' => $password]);

        User::create($data);
        Alert::success('Success', 'Data Telah Terinput');
        return redirect()->back();
    }

    public function edit_bukan_pj($id)
    {
        $user2 = DB::table('users')->where('id', $id)->first();
        

        $ruangan = DB::table('ruangan')->get();

        return view('bukan_pj.edit', compact('ruangan', 'user2'));
    }

    public function update_bukan_pj(Request $request)
    {
        
        DB::table('users')->where('id',$request->id)->update([
            'name'=>$request->name,
            'email'=>$request->email,
            'username'=>$request->username,
           
        ]);

        Alert::success('Success', 'Data Telah Terupdate');
        return redirect('/bukan_pj');
    }


}

resources/views/user/edit.blade.php
@extends('layouts.layout')
@section('content')
<title>Edit Data Users</title>
<div class="card-header py-3">
  <h6 class="m-0 font-weight-bold text-dark">Edit Data</h6>
</div>
<div class="card-body">
    <div class="x_content">
            <form action="{{ url('/user/update') }}" method="post">
                    @csrf
                  <div class="form-group">
                      <label for="">Nama</label>
                      <input type="hidden" name="id" class="form-control" value="{{$user2->id}}" required placeholder="Masukan Nama">
                      <input type="text" name="name" class="form-control" value="{{$user2->name}}" required placeholder="Masukan Nama">
                  </div>
                  <div class="form-group">
                        <label for="">Username</label>
                        <input type="text" name="username" class="form-control" value="{{$user2->username}}" required placeholder="Masukan Username">
                        {{-- @error('username')
                                <span class="help-block">
                                    <strong style="color:red">{{ $message }}</strong>
                                </span>
                        @enderror --}}
                    </div>
                   <div class="form-group">
                        <label for="">Email</label>
                        <input type="email" name="email" class="form-control" value="{{$user2->email}}" required placeholder="Masukan email">
                        {{-- @error('email')
                            <span class="help-block">
                                <strong style="color:red">{{ $message }}</strong>
                            </span>
                        @enderror --}}
                    </div>
                
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div> 
            </form>
    </div>
@endsection

resources/views/user/home.blade.php
@extends('layouts.layout')
@section('content')
<title>Dashboard</title>
</div>
 <div class="row"> 
   <div class="col-xl-6 col-md-12 mb-4">
    <div class="card border-left-dark shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">Total Barang</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{$hitung_barang}}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-6 col-md-12 mb-4">
    <div class="card border-left-dark shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">Total Barang Rusak</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{$hitung_dalam + $hitung_luar  }}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-dark shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">Total Barang Masuk</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{$hitung_masuk}}</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-calendar fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Total Barang Keluar</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{$hitung_keluar}}</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Pending Requests Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Total Barang Ruangan</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{$hitung_ruangan}}</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-comments fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
 </div>
 <div class="card shadow mb-4">

@endsection

resources/views/user/view.blade.php
@extends('layouts.layout') @section('content')
<title>Data Admin</title>
<div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-dark">Data Admin</h6>
</div>
<div class="card-body">
    <div class="table-responsive">
        <div>
             @error('email')
                            <span class="help-block">
                                <strong style="color:red">{{ $message }}</strong>
                            </span>
            @enderror
            <br>
             @error('username')
                            <span class="help-block">
                                <strong style="color:red">{{ $message }}</strong>
                            </span>
                       
            @enderror
        </div>
         
        <button class="btn btn-success" data-toggle="modal" data-target="#tambah">Tambah Data</button>
        <br>
        <br>
        <table id="dataTable" class="table table-bordered" cellspacing="0">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama</th>
                    <th>Email</th>
                    <th>Username</th>
                    <th>Password</th>
                    <th>Level</th>
                    <th>Opsi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($user as $i => $u)
                <tr class="data-row">
                    <td class="align-middle iteration">{{ ++$i }}</td>
                    <td class="align-middle name">{{ $u->name }}</td>
                     <td class="align-middle name">{{ $u->email }}</td>
                    <td class="align-middle username">{{ $u->username }}</td>
                    <td class="align-middle password">Password Tidak Ditampilkan</td>
                    <td class="align-middle level">{{ $u->level }}</td>
                   
                    <td>
                        <div class="row">
                                <a href="{{ url ('/user/edit/'.$u->id.'') }}" class="btn btn-primary btn-sm ml-2">Edit</a>
                            {{-- <form action="{{ route('user.destroy',$u->id) }}" method="POST">
                                @csrf @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm ml-2">Delete</button>
                            </form> --}}
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

<div id="tambah" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Masukan Data</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('user.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="">Nama</label>
                        <input type="text" name="name" class="form-control" required placeholder="Masukan Nama">
                    </div>
                    <div class="form-group">
                        <label for="">Email</label>
                        <input type="email" name="email" class="form-control" required placeholder="Masukan mail">
                      
                    </div>
                    <div class="form-group">
                        <label for="">Username</label>
                        <input type="text" name="username" class="form-control" required placeholder="Masukan Username">
                      
                    </div>
                    <div class="form-group">
                        <label for="">Password</label>
                        <input type="password" name="password" class="form-control" required placeholder="Masukan Password">
                    </div>
                    <input type="hidden" name="level" value="admin">
                 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>

 @endsection